/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JavaOOP_SWING.subframe;

import java.awt.Graphics2D;
import java.util.Random;

/**
 *
 * @author nguye
 */
public class Mang1chieu extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mang1chieu
     */
    int[] a;
    
    public Mang1chieu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPannel = new javax.swing.JPanel();
        btn1chieu = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vẽ mảng 1 chiều");

        pnPannel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnPannelLayout = new javax.swing.GroupLayout(pnPannel);
        pnPannel.setLayout(pnPannelLayout);
        pnPannelLayout.setHorizontalGroup(
            pnPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );
        pnPannelLayout.setVerticalGroup(
            pnPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        btn1chieu.setText("Vẽ mảng 1 chiều");
        btn1chieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1chieuActionPerformed(evt);
            }
        });

        btnSort.setText("Sắp xếp mảng 1 chiều");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn1chieu)
                            .addComponent(btnSort))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn1chieu, btnSort, pnPannel});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn1chieu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSort)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1chieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1chieuActionPerformed
        Graphics2D gs = (Graphics2D) pnPannel.getGraphics();
        
        int maxX = pnPannel.getWidth();
        int maxY = pnPannel.getHeight();
        int step = 5;
        int n = maxX / step;
        a = new int[n];
        Random rnd = new Random();
        for (int i = 0; i < a.length; i++) {
            a[i] = rnd.nextInt(maxY);
        }
        
        int beginX = 0, beginY = 0;
        gs.clearRect(0, 0, maxX, maxY);
        for (int i = 0; i < n; i++) {
            gs.drawRect(beginX, maxY - a[i], step, a[i]);
            beginX += 5;
        }
    }//GEN-LAST:event_btn1chieuActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        Graphics2D gs = (Graphics2D) pnPannel.getGraphics();
        
        int maxX = pnPannel.getWidth();
        int maxY = pnPannel.getHeight();
        int step = 5;
        int n = maxX / step;
        
        int beginX = 0, beginX2 = 0;
        
        for (int i = 0; i < n - 1; i++) {
            for (int j = i + 1; j < n; j++) {
                if (a[i] > a[j]) {
                    int temp = a[i];
                    //xoa cột a[i]
                    gs.clearRect(beginX, maxY - a[i], step, a[i]);
                    //ve côt a[i] mới
                    a[i] = a[j];
                    gs.drawRect(beginX, maxY - a[i], step, a[i]);
                    //xoa cột a[j] cũ
                    beginX2 = j * step;
                     gs.clearRect(beginX2, maxY - a[j], step, a[j]);
                    //ve côt a[i] mới
                    a[j] = temp;
                    gs.drawRect(beginX2, maxY - a[j], step, a[j]);     
                }
            }
            beginX += step;
        }
    }//GEN-LAST:event_btnSortActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1chieu;
    private javax.swing.JButton btnSort;
    private javax.swing.JPanel pnPannel;
    // End of variables declaration//GEN-END:variables
}
